apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team1
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team1
  name: administrator
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"] 
