apiVersion: v1
kind: Namespace
metadata:
  name: team1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
  namespace: team1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: team1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: team1
